### PR TITLE
AI Nodes Updated

### PR DESCRIPTION
**Pull request by HaloDiehards**
All AI-related node pages now have a new section "Description", with the descriptions that you see in the Halo Infinite node menus.

AI and AI Advanced categories have new Input and Output sections as well as their node images.

### CODE REVIEW

**Comment by Okom1** [comment]
Move image files into `\.gitbook\assets` instead of the folder where the article goes. Update image paths afterwards.

**Comment by HaloDiehards** [comment]
> Move image files into `\.gitbook\assets` instead of the folder where the article goes. Update image paths afterwards.

I'm confused. Do you want me to install Gitbook and then import my branch into Gitbook, and then redo the images and then push?

**Comment by Okom1** [comment]
> > Move image files into `\.gitbook\assets` instead of the folder where the article goes. Update image paths afterwards.
> 
> I'm confused. Do you want me to install Gitbook and then import my branch into Gitbook, and then redo the images and then push?

Put the images in this folder https://github.com/The-Scripters-Guild/ForgeWiki/tree/main/.gitbook/assets that is in the repo.

**Comment by HaloDiehards** [comment]
> Put the images in this folder https://github.com/The-Scripters-Guild/ForgeWiki/tree/main/.gitbook/assets that is in the repo.

I don't have permission to do that.
image

**Comment by Okom1** [comment]
Well, ofc not to the main repo, but the equivalent folder in your fork that you're trying to merge https://github.com/HaloDiehards/ForgeWiki/tree/main/.gitbook/assets

**Comment by Okom1** [comment]
> Well, ofc not to the main repo, but the equivalent folder in your fork that you're trying to merge https://github.com/HaloDiehards/ForgeWiki/tree/main/.gitbook/assets

Do this within your VS Code environment, there should be a /.gitbook/assets folder. Move the images there and update the pull request.

**Comment by HaloDiehards** [comment]
> > Well, ofc not to the main repo, but the equivalent folder in your fork that you're trying to merge https://github.com/HaloDiehards/ForgeWiki/tree/main/.gitbook/assets
> 
> Do this within your VS Code environment, there should be a /.gitbook/assets folder. Move the images there and update the pull request.

Ok, thank you for directly pointing me to the assets folder. Images have been moved there, pages updated to use those images, and pushed the changes to my main branch. Do I need to cancel this pull request and do a new one, or does it update this pull request when I make changes?

**Comment by HaloDiehards** [comment]
Looks like it pulls the most recent, so it would include the fixes.

**Comment by Okom1** [comment]
Looks good, approved.

**Comment by Okom1** [comment]
> Kewl. What has to happen for the wiki pages to be updated? (just curious on the process)

They'll get updated automatically after the merge. I had a delayed merge there accidentally.

**Pull request merged**
